### ISSUE TITLE
Feedback 

### ISSUE THREAD

**Issue by kjappelbaum** [marda-alliance/metadata_extractors_schema#2]
I was looking at your filetype schema example and it looks at bit similar to what I started using to describe the cheminfo parsers. For example, https://github.com/cheminfo/isotherm-analysis/blob/b60e41749cc78a2dbf4961696854c2d995e01ac5/package.json#L65-L105. 

This was then automatically collected by the "registry" to make it a bit searchable. The most important thing in our "schema" was perhaps the link to an example file (as simply the name of the instrument and extension oftentimes doesn't describe much). Perhaps one could also consider adding it here.

To make this possible, I once started a "chemical files registry" here, where I use also a `yml` schema similar to yours: https://github.com/kjappelbaum/chemical-files-registry/blob/master/fileDescriptions/analyticalMethods/thermogravimetricAnalysis/ta-txt/description.yml. 

I didn't have any time to work on this, but the idea was to collect example files and link to them (and the filetype schema) from the parser registry. 
Also, I found it useful to include notes to other potential users about the filetype, e.g. issues I faced when implementing the parser.

**Comment by ml-evs** [comment]
Thanks for reminding me of this @kjappelbaum. Do you still have the schema you used in that project? The example files is a good idea, and could be incorporated into https://github.com/marda-alliance/metadata_extractors_registry for sure.

**Comment by hgoerzig** [comment]
Do you think it would make sense to also add associated readingor usage software, not only producing software?
The other thing I was thinking about is, that it might be good to use standard vocabulary and PIDs or URLs additionally to the description. Like e.g. mime types for the base format, github links or PIDs for software, PIDs also for some instruments.
For the instrumentsection it might be good to have a look at https://zenodo.org/record/6396467#.Y6Q0toSZM-V there they use manufacturar, model, and instrument type. Just if the registry later should be integrated with other registries. For the software there might be something similar.

There is a typo: NeXus not NeXuS (before it is everywhere)

**Comment by hgoerzig** [comment]
Have you thought about looking at RO-Crate [1]? Or the DataType registry [2]? And FAIR Digital Objects FDOs [3]? Just for integration into the wider world? (Mainly [1] and [2])
[1] https://www.researchobject.org/ro-crate/1.1/data-entities.html
[2] https://www.rd-alliance.org/group/data-type-registries-wg/outcomes/data-type-registries 
[3] https://fairdo.org/

**Comment by ml-evs** [comment]
> Do you think it would make sense to also add associated readingor usage software, not only producing software? 

I think the idea would then be that the registry contains all of our contributed software such that it links to the persistent ID of the corresponding file type. I guess we could make this link work both ways if it would be useful?

> The other thing I was thinking about is, that it might be good to use standard vocabulary and PIDs or URLs additionally to the description. Like e.g. mime types for the base format, github links or PIDs for software, PIDs also for some instruments. For the instrumentsection it might be good to have a look at https://zenodo.org/record/6396467#.Y6Q0toSZM-V there they use manufacturar, model, and instrument type. Just if the registry later should be integrated with other registries. For the software there might be something similar.

Yes, absolutely! If you have specific suggestions for definitions we can add them in the `slot_uri` section of the schema, which is intended as a place to provide semantic mappings

> There is a typo: NeXus not NeXuS (before it is everywhere)

Thanks, fixed!

**Comment by ml-evs** [comment]
> Have you thought about looking at RO-Crate [1]? Or the DataType registry [2]? And FAIR Digital Objects FDOs [3]? Just for integration into the wider world? (Mainly [1] and [2]) [1] https://www.researchobject.org/ro-crate/1.1/data-entities.html [2] https://www.rd-alliance.org/group/data-type-registries-wg/outcomes/data-type-registries [3] https://fairdo.org/

We've discussed [1] and [3] in the past for related projects; if you have experience with them then it would be great to discuss at a later meeting as I'm not sure how we would directly integrate.

I wasn't aware of [2] (my RDA involvement is limited to the materials WG mostly). It sounds like they went through a similar process to this nearly 10 years ago, so we should definitely read about what did and didn't work. Do you know if they are still active? The RDA website can be a bit of maze but it looks like they disbanded last year.

**Comment by PeterKraus** [comment]
Thanks a lot for your comments. I've made two of your suggestions into separate, perhaps more systematically named issues - personally I think we should implement both of those.

> Do you think it would make sense to also add associated reading or usage software, not only producing software? 

I also believe this is the job for the registry, not for the schema.

> Have you thought about looking at RO-Crate [1]? Or the DataType registry [2]? And FAIR Digital Objects FDOs [3]?

I wasn't aware of either. For version `1.0` (or whatever the first release will be called) we've agreed to not concern ourselves with the output data (or its schema) at all. However, I think it might be prudent to keep track of all of these open data standards and their actionable schemas, as there might be value in ensuring that a parser that says it produces, say, NeXus really does in version `2.0`.

**Comment by PeterKraus** [comment]
I have triaged off these ideas into the respective issues (#3, https://github.com/marda-alliance/metadata_extractors_registry/issues/9, and https://github.com/marda-alliance/metadata_extractors_schema/pull/9#pullrequestreview-1268733730). I'll close this issue for now, but feel free to reopen this if you think there's something forgotten.
