### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by ml-evs** [marda-alliance/metadata_extractors_schema#29]
Currently each extractor object has a defined version and installation instructions that are tied to that version. This will cause a problem as soon as the next version of any extractor is released... we need some thought on how to handle this wrt. the registry, and executing extractor code locally.

**Comment by PeterKraus** [comment]
Idea: if `version` of an `Extractor` is populated, the "unique ID" of that `Extractor` becomes `$id-$version`. We should also encourage `Extractor` authors to use the `yadg~=5.0` notation for their `pip` installs (which will install latest `yadg-5.x` version).

**Comment by PeterKraus** [comment]
Following our latest office hours meeting, we have decided to kick this can down the road.

At the moment, and for the forseeable future, it's the responsibility of the author of the `Extractor` file to specify a reasonable set of versions of the extractor code. I guess we'll decide how to handle versioned `Extractors` once we have a first case where two versions of the extractor would need two `Extractor` files further down the line.

**Comment by PeterKraus** [comment]
@ml-evs On a second thought, I'd like to reopen this to get your opinion. 

Currently, we have a `version` entry in the `Extractor` schema, which is not used for anything. In line with the above, I'd suggest we remove the slot completely to avoid confusion until we have a better idea how to deal with versions across `Extractors` and `FileTypes`

Second, there are `FileTypes` (such as NetCDF or even the MPR files) which are versioned. A proper solution should allow these versions be listed within a `FileType` definition (eventually perhaps with identifying magic bits, if known). Similarly, the `Extractors` should be able to target a specific subset of `FileType` versions, or all of them (default). Thoughts?

**Comment by PeterKraus** [comment]
Conclusions:
- version requirement for the `Extractor` can be added in the installation instructions and tightened appropriately; as necessary, multiple `Extractors` can be created for each code (something like qt4 and qt5 packages).
- versions of `FileTypes` have to be handled within the extractor codes, `FileType` detection is difficult enough
