### ISSUE TITLE
Allow specification of minimum Python version for `pip` installation method

### ISSUE THREAD

**Issue by ml-evs** [marda-alliance/metadata_extractors_schema#35]
Currently this is the only additional piece of information required "out-of-band", i.e., which `pip` do I actually run this command with. This info can also be used to tailor the virtual environments made by the API, potentially even allowing automated installation of older versions where necessary (though this will break pickle for really old versions...)

**Comment by PeterKraus** [comment]
I had to have a look at the schema to understand what you want here. The version is not that of `pip`, but that of `python`. But it's clear now, and a good idea. I'll continue the discussion in the PR.
